# Generated by Django 3.1.4 on 2020-12-14 09:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20190905_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='date1',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='book',
            name='time1',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='bus',
            name='date1',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='bus',
            name='flight_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='bus',
            name='time1',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='book',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='book',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='bus',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='bus',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
