# Generated by Django 3.1.4 on 2020-12-14 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20201214_0130'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='flight_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
