# Generated by Django 3.1.4 on 2020-12-14 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20201214_1848'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bus',
            new_name='Flight',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='busid',
            new_name='flightid',
        ),
    ]
