# Generated by Django 3.1.4 on 2020-12-14 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20201214_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='nos',
            field=models.DecimalField(decimal_places=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='flight',
            name='nos',
            field=models.DecimalField(decimal_places=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='flight',
            name='rem',
            field=models.DecimalField(decimal_places=0, max_digits=6),
        ),
    ]
